### ISSUE TITLE
Leaf texture not rendering in certain areas.

### ISSUE THREAD

**Issue by BadComoc** [Hopson97/open-builder#121]
![Image of Issue](https://i.imgur.com/BwzXlGX.png)
I don't exactly have any more information on what's causing this.
It happens around certain areas of the map.

**Comment by b0guslaw** [comment]
Please provide more detail about this bug. Look at other bug reports to see the format that was used. 
Tl;dr: Describe the bug, steps to (reliably) reproduce, expected behavior, actual behavior, screenshots, environment and additional information is missing from this report
