### ISSUE TITLE
cmake version issue

### ISSUE THREAD

**Issue by namedtoaster** [Hopson97/open-builder#124]
Just cloned the repo on my Ubuntu distro - when I try to run the install script I get a cmake verision error:

`CMake 3.10 or higher is required. You are running version 3.5.1`

Doesn't really make sense to me. Can somebody smarter than me tell me what's happening?

**Comment by b0guslaw** [comment]
Please ensure your locally installed CMake version is at least 3.10

**Comment by ivanka2012** [comment]
You need CMake 3.10. You can try downloading it by `sudo apt-get update` and the `sudo apt-get upgrade`, or you can build the latest version from [GitHub](https://github.com/Kitware/CMake).

**Comment by b0guslaw** [comment]
> You need CMake 3.10. You can try downloading it by `sudo apt-get update` and the `sudo apt-get upgrade`, or you can build the latest version from [GitHub](https://github.com/Kitware/CMake).

This is outside the scope of this issue, but do not use apt-get, instead use apt

**Comment by b0guslaw** [comment]
The lowest minimum version is 3.10

10 is a higher number than 5, therefore 3.5 is lower than 3.10
