### ISSUE TITLE
Remove FPS spike from updating blocks

### ISSUE THREAD

**Issue by arclicious** [Hopson97/open-builder#128]
# Remove FPS spike from updating blocks

## Describe the bug
Whenever a block is updated (eg. placed or removed), I experience a significant lag spike while the block is updating.

## To Reproduce
1. Place/remove block.

## Expected behavior
I expected that the blocks would update without any impact on performance.

## Screenshots
None.

## Desktop (please complete the following information):
 - OS: PC
- Graphics Card: NVIDIA GeForce GTX 1650

**Comment by Hopson97** [comment]
Are you building the game using release or debug mode?

**Comment by arclicious** [comment]
I am using debug mode.

**Comment by Hopson97** [comment]
Build in release mode to fix this, debug mode will basically always be a bit slower and there's not much that can be done about this
