### ISSUE TITLE
Blocks rendering as wireframes instead of full blocks

### ISSUE THREAD

**Issue by arclicious** [Hopson97/open-builder#129]
# Blocks rendering as wireframes instead of full blocks

## Describe the bug
All of the blocks in the game were rendering as a wireframe of the block.

## To Reproduce
I actually don't know. I had just restarted the build from Visual Studio because I accidentally closed it.

## Expected behavior
I expected the blocks to render correctly, instead of as wireframes.

## Screenshots
I accidentally pressed the Escape key on my keyboard so that I could get a screenshot of the issue.

## Desktop (please complete the following information):
 - OS: PC
- Graphics Card: NVIDIA GeForce GTX 1650

## Additional context
I really don't have any idea on what is going on here.

**Comment by kiroma** [comment]
There's a key which changes rendering mode to wireframe, maybe you pressed it by accident?

**Comment by Hopson97** [comment]
This is infact a feature :P When you hit the P key I think, it switches over to wireframe renders
