### ISSUE TITLE
Render Distance / Fog

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/open-builder#146]
## Describe your suggestion

Allow player to set render distance (in 3 directions XYZ), only rendering chunks in a certain "radius" around the player.

Optional, could use fog as well to make it appear a bit cleaner.

Optional, use "F" key to decrease/increase render distance as needed, much like older Minecraft versions for nostalgia.

## Implementations ideas [optional]

The position of the camera is already being passed into the chunk render functions, this can be used to work out distance from camera.

 Maybe use Manhattan distance rather than euclidean distance for slightly better performance.

**Comment by UglySwedishFish** [comment]
Are you sure you want people to be able to set it for both X & Z? I can see there being some point in allowing people to set it for height / ground level but X & Z separately just seems needlessly complicated

**Comment by Hopson97** [comment]
What I meant was a single render distance that works in the XYZ, not 3 separate ones

**Comment by UglySwedishFish** [comment]
Oh, fair enough then.
