### ISSUE TITLE
Indices are taking up memory instead of helping

### ISSUE THREAD

**Issue by bojosos** [Hopson97/open-builder#153]
Rendering the blocks using indices in this case is not really helping! (I have barely looked at your code and my assumptions are made mostly based on your shader)

You render a block face using 4 vertices -> 16 bytes + 24 bytes for indices = 40 bytes
You could also render a block face using 6 vertices -> 36 bytes
Just use glDrawArrays

**Comment by Hopson97** [comment]
You are correct.

However, I have tried this (https://github.com/Hopson97/open-builder/pull/142) and although memory usage was decreased, performance was grossly decreased by a weirdly large amount.

And so decided to stick with elements.
