### ISSUE TITLE
Water not rendering when a block is placed on top of it

### ISSUE THREAD

**Issue by nagmagit** [Hopson97/open-builder#156]
# Bug name
Water rendering problem

## Description
When a block is placed on top of a block of water, that block of water doesn't get rendered.

## To Reproduce
1. Run the game.
2. Go to a source of water.
3. Place a block just above the water level.
4. Contemplate.

## Expected behavior
The top face of the water block **should** get rendered.

## Screenshots
![image](https://user-images.githubusercontent.com/4872133/74762577-e3c48f00-525c-11ea-8b58-ca7c780302bb.png)

## Desktop
Ubuntu 18.04

## Additional context
Caused in [the chunk mesh generation file](https://github.com/Hopson97/open-builder/blob/master/src/client/world/chunk_mesh_generation.cpp#L99).

We could check if the current voxel contains gaps on it (which will make it work with stairs, slabs, doors, etc) by adding a flag to the VoxelData struct that indicates which faces it won't fully cover.

**Comment by Hopson97** [comment]
Good issue. I believe this would also happen with leaf blocks.

Also your solution makes sense. A flag like "isOpaque" could be added, allowing the meshbuilding to code to add faces when it is set to false.

**Comment by nagmagit** [comment]
It might be necessary to specify which faces have to be rendered. Not only because of optimization reasons (1 extra face vs all 6 faces), but because the faces inside water shouldn't be rendered, only the faces that contact with other blocks.

I'll be working on implementing this, if that's not a problem of course.

**Comment by Hopson97** [comment]
That is fine :)

> It might be necessary to specify which faces have to be rendered. 

This is true, for now though (to keep things nice and simple, and the face I don't have anything like stairs or slabs in the game for now), it could just be all faces.

> but because the faces inside water shouldn't be rendered, 

IIRC, the chunk meshing code will not add block faces if the neighbour block is the same (This is what allows the terrain faces to render underwater, while "underwater faces" are not rendered)

**Comment by nagmagit** [comment]
Good news:

![image](https://user-images.githubusercontent.com/4872133/74798987-13e84e00-52ae-11ea-8dff-64b3aada207c.png)

Bad news (but hey, the trees are visible underwater :D):

![image](https://user-images.githubusercontent.com/4872133/74798893-cbc92b80-52ad-11ea-95e5-bbd9b282ff54.png)

As a temporary fix, it's been hardcoded that fluids only render their sides when facing air.
