### ISSUE TITLE
Allow GitHub actions to recognize std::filesystem, std::optional etc

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/open-builder#174]
## Describe your suggestion
The current GitHub actions setup fails to build any code that uses certain C++17 features, such as `std::filesystem` and `std::optional`.

As a result of this I am reluctant to use these features, despite their usefulness. 

## Implementations ideas [optional]

I have tired to find a solution to this, but have not.

**Comment by D3PSI** [comment]
I have also had this problem for a long time now (in other projects as well). Also still desperately looking for a solution...

**Comment by D3PSI** [comment]
The thing is, you can try to reinstall the compilers with a version that supports this (g++-8 should suffice if I'm correct, not 100% sure, would have to check), but I have tried this in other projects and it somehow still does not work. See [this](https://github.com/D3PSI/nautilus/runs/523909431) job where I tried to upgrade the gcc and g++ compilers to version 8. I even exported the new values to the corresponding CC and CXX environment variables...

**Comment by D3PSI** [comment]
Alright, I did some experimenting on one of my projects. I will propose an update for the automatic install script shortly, we'll see whether that does the trick, let us hope ;)

**Comment by D3PSI** [comment]
This can probably be closed now with #175 merged :)

**Comment by Hopson97** [comment]
Thanks again :)
