### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by romanwojciechowski** [Hopson97/open-builder#207]
I get an error when I try to compile

I followed the instructions - https://github.com/Hopson97/open-builder/blob/master/docs/building/Building_linux_cmake.md

 - OS: Linux Manjaro
![Screenshot from 2020-08-09 09-21-33](https://user-images.githubusercontent.com/59702817/89727068-e345cd80-da21-11ea-9448-cc81631821da.png)

**Comment by Dearast** [comment]
Hello,

The easiest thing you can do is add this:
`#include<string>`
to the open-builder/src/server/world/terrain_generation.h like this:
```
#pragma once

#include <array>
#include <common/world/coordinate.h>
#include <common/world/world_constants.h>
#include <vector>
#include <string> // this is what you want to include there for generateSeed where is it used

class ChunkManager;
class BiomeDataManager;
class VoxelDataManager;

std::vector<ChunkPosition> generateTerrain(ChunkManager& chunkManager, int chunkX,
                                           int chunkZ, const VoxelDataManager& voxelData,
                                           const BiomeDataManager& biomeData, int seed,
                                           int worldSize);

float generateSeed(const std::string& input);
```

I'm new here in open sources, so I don't know how to report a possible change.
