### ISSUE TITLE
Lower Water Level

### ISSUE THREAD

**Issue by Starman0620** [Hopson97/open-builder#212]
This would just be a small change, but lowering the level that water renders at by a tiny bit would greatly improve the looks of the water. This is a technique used by various other voxel games and it works brilliantly.

I've already got a rather simple implementation of this that I can add to a PR if this is accepted. (only creating this issue to follow the contributing steps)

Edit: Sorry that there's no proper label or anything on this, I just used the link from the Contributing page to create the issue which bypasses the Bug and Feature selection thing, should probably fix that :P

**Comment by Hopson97** [comment]
I think I had implemented previously (IIRC the water level was lowered in the shader by 0.2 or something, and then also added a wave effect) and I can agree it looks infinitely better. However, I had some plans that I never got around to finishing which would cause this to look kind of strange (Image water from the side view). For that reason, the water level remains at just one for now :P 

Thanks for comment anyways! :)
