### ISSUE TITLE
Ctrl-D in server console 

### ISSUE THREAD

**Issue by HectorPeeters** [Hopson97/open-builder#22]
When hitting Ctrl-D in the server console on linux, the server keeps printing "> " to the screen until the server is manually terminated. This is a problem because of the EOF being send by the terminal.

Steps to reproduce:
`./scripts/run.sh -server 8`
Then press `Ctrl-D`

Screenshot:
![Selection_017](https://user-images.githubusercontent.com/10477397/71291337-94ec9d00-2372-11ea-8904-5178883b5060.png)

Potential solution:
`if (line == "exit") {`
Could get replaced by
`if (std::cin.eof() || line == "exit") {`
which solves the eof problem

**Comment by Hopson97** [comment]
merged #23
