### ISSUE TITLE
Chunk triangle optimization

### ISSUE THREAD

**Issue by hebriel** [Hopson97/open-builder#40]
Hey Hopson, did you plan on doing the chunk optimization by yourself for the series ?
like 2 triangles per quad with the same texture instead of 2 triangles per BlockFace ?

**Comment by Hopson97** [comment]
If you mean greedy mesh algorithm, then ye I eventually plan to. Probably not until the current system is an actual problem though :stuck_out_tongue:

**Comment by hebriel** [comment]
alright, i won't touch it then. closing issue
