### ISSUE TITLE
Add instruction prompt

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/open-builder#55]
When launching the game, it would nice if the terminal window outputted the controls before launching the client (And maybe a 'press enter to continue).

This would be done in the launchClient function of main.cpp

https://github.com/Hopson97/open-builder/blob/master/src/main.cpp#L154

**Comment by Hopson97** [comment]
Bonus: Make it so that it mentions default settings can be set using config.txt

**Comment by Hopson97** [comment]
Side note

Meant to be  for when the client and server are ran separately, but to prevent the server timing out using the "launch both" option :, 

Could pass a boolean to client launch function check how the application was started, so if it was started as standalone client (aka directly from int main)  then it would ask the user to press enter to continue, othwise it would skip this and continue to launch

**Comment by Dmendoza99** [comment]
I would love to help you out with this issue, it seems simple to start helping haha :laughing:

**Comment by Dmendoza99** [comment]
What do you think about this @Hopson97 ?
![Screenshot from 2020-01-19 20-27-03](https://user-images.githubusercontent.com/30415552/72694309-3134cb80-3afa-11ea-9fe5-3abea8ec53d3.png)
