### ISSUE TITLE
Use seed for world generation 

### ISSUE THREAD

**Issue by Hopson97** [Hopson97/open-builder#69]
** Suggestion Title **
Using a seed to create different world gen

** Describe your suggestion **
Right now the world generation is the same every single time
However to be more interesting, it would be better if a seed were somehow used to create different results

** Implementations ideas [optional]**

Not sure

**Comment by rehwinkel** [comment]
Should the seed be stored in a world-file of some sort?

**Comment by Hopson97** [comment]
Probably will be yes.

For now there is no world file though, so not worrying about this for now.

The way I am seeding atm is by passing a seed into the third parameter of "3D Simplex Noise", which would give a unique slice of that noise, but its not the most effective (as you can imagine, a seed like 3423 would be basically the same as 3424)

**Comment by rehwinkel** [comment]
#98

**Comment by Hopson97** [comment]
Solved by #98
