### ISSUE TITLE
Crosshair + overlay/ui framework

### ISSUE THREAD

**Issue by marbles-box** [Hopson97/open-builder#70]
** Suggestion Title **
Implement crosshair + framework for ui

** Describe your suggestion **
Simply draw a crosshair sprite at the center of the game window, as well as a framework for easily implementing other similar elements to be drawn as an overlay (e.g. UI, HUD). Crosshair is mainly for ease of knowing what block you're looking at.

** Implementations ideas [optional]**
Possibly just define a class that's not too much more than an sfml sprite.

**Comment by Hopson97** [comment]
SFML won't work unfortunately, it does not play well with user-defined OpenGL stuff

But good ideas 👍

**Comment by Hopson97** [comment]
Reoprening as it is a needed feature, and can be implemented using OpenGL anyways

**Comment by Ruixel** [comment]
https://github.com/Hopson97/open-builder/pull/96
Added/improved the gui framework for lua and now has neat crosshair

**Comment by Ruixel** [comment]
PR pushed, closing now
